---
general_user: "{{ vault_general_user }}"
general_password: "{{ vault_general_password }}"
general_sshd_ports: "{{ vault_general_sshd_ports }}"
general_ssh_keys: "{{ vault_general_ssh_keys }}"
general_github_access_token: "{{ vault_general_github_access_token }}"

media_vlc_user: "{{ vault_media_vlc_user }}"
media_vlc_port: "{{ vault_media_vlc_port }}"
media_vlc_password: "{{ vault_media_vlc_password }}"
media_spotify_username: "{{ vault_media_spotify_username }}"
media_spotify_password: "{{ vault_media_spotify_password }}"
media_spotifyd_device_type: "{{ vault_media_spotifyd_device_type }}"

transmission_shared_group: "{{ vault_transmission_shared_group }}"
transmission_download_user: "{{ vault_transmission_download_user }}"

git_full_name: "{{ vault_git_full_name }}"
git_email: "{{ vault_git_email }}"

ssh_entries: "{{ vault_ssh_entries }}"

syncthing_port: "{{ vault_syncthing_port }}"
