---
- name: "Install vim, neovim and dependencies"
  apt:
    name:
      - "vim"
      - "xsel"
      - "ripgrep"
      - "libvterm-dev"
      - "neovim"
      - "python3-neovim"
    state: "present"
  become: yes

- name: "Download neovim configuration repository"
  git:
    repo: "{{ neovim_config_repo }}"
    dest: "{{ neovim_directory }}"
    depth: 1
    clone: yes
    update: yes
