---
- name: "Install vim and dependencies"
  apt:
    name:
      - "vim"
      - "xsel"
      - "ctags"
      - "ripgrep"
      - "libvterm-dev"
      - "neovim"
      - "python-neovim"
    state: "present"
  become: yes

- name: "Install plugin dependencies"
  pip:
    name:
      - "pynvim"
      - "Send2Trash"
    state: "latest"
    extra_args: "--user"

- name: "Download Nvim configuration repository"
  git:
    repo: "{{ nvim_config_repo }}"
    dest: "{{ neovim_directory }}"
    depth: 1
    clone: yes
    update: yes

- name: "Create folder for Neovim dictionaries"
  file:
    path: "{{ neovim_spell_dest }}"
    state: "directory"

- name: "Install Neovim dictionaries"
  get_url:
    url: "{{ neovim_spell_url }}/{{ item }}"
    dest: "{{ neovim_spell_dest }}"
  with_items: "{{ neovim_spell_dictionaries }}"
