---
- name: "Get currently neovim version"
  shell: "nvim --version | head -n 1"
  failed_when: no
  changed_when: no
  register: neovim_installed_version

- name: "Install neovim dependencies"
  apt:
    name:
      - "ninja-build"
      - "gettext"
      - "libtool"
      - "libtool-bin"
      - "autoconf"
      - "automake"
      - "cmake"
      - "g++"
      - "pkg-config"
      - "unzip"
      - "python-neovim"
      - "python3-neovim"
  become: yes
  when: neovim_installed_version.stdout is not defined or neovim_installed_version.stdout != neovim_version_output

- name: "Download and install neovim"
  block:
    - tempfile: suffix="neovim" state="directory"
      register: tempdir
    - git: repo="{{ neovim_repo }}" dest="{{ tempdir.path }}" version="{{ editor_neovim_version }}"
    - command: "make CMAKE_BUILD_TYPE=Release"
      args:
        chdir: "{{ tempdir.path }}"
    - command: "make install"
      args:
        chdir: "{{ tempdir.path }}"
  always:
    - file: path="{{ tempdir.path }}" state="absent"
  become: yes
  when: neovim_installed_version.stdout is not defined or neovim_installed_version.stdout != neovim_version_output
