---
- name: "Install git"
  apt:
    name: "git"
    state: "present"
  become: yes

- name: "Copy git configuration files"
  template:
    src: "git/{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: "0600"
  with_items:
    - "gitconfig"
    - "gitignore"
