---
- name: "Install shell utilities"
  apt:
    name:
      - "easy-rsa"
      - "rsync"
      - "xsel"
      - "xdotool"
      - "wmctrl"
      - "ripgrep"
      - "powerline"
      - "cryptsetup"
      - "lsof"
      - "tldr"
      - "jq"
      - "ncdu"
      - "tmux"
      - "unzip"
      - "time"
      - "wget"
      - "tig"
      - "fzf"
    state: "present"
  become: yes

- import_tasks: "git.yml"
- import_tasks: "htop.yml"
- import_tasks: "urlview.yml"
- import_tasks: "neofetch.yml"
