---
- name: "Install shell utilities"
  apt:
    name:
      - "easy-rsa"
      - "rsync"
      - "xsel"
      - "xdotool"
      - "wmctrl"
      - "ripgrep"
      - "powerline"
      - "cryptsetup"
      - "lsof"
      - "jq"
      - "ncdu"
      - "tmux"
      - "unzip"
      - "time"
      - "wget"
      - "tig"
      - "fzf"
      - "fastfetch"
      - "btm"
      - "git"
    state: "present"
  become: yes

- name: "Copy bash configuration file"
  template:
    src: "bash/bashrc.j2"
    dest: "~/.bashrc"
    mode: "0600"

- name: "Copy bash related configuration files"
  template:
    src: "bash/{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: "0600"
  with_items:
    - "bashrc"
    - "inputrc"

- name: "Copy git configuration files"
  template:
    src: "git/{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: "0600"
  with_items:
    - "gitconfig"
    - "gitignore"
