---
- name: "Install neofetch and dependencies"
  apt:
    name: 
      - "neofetch"
      - "x11-xserver-utils"
  become: yes

- name: "Create folder for neofetch configuration"
  file:
    path: "{{ neofetch_directory }}"
    state: "directory"

- name: "Copy neofetch configuration file"
  template:
    src: "neofetch/config.j2"
    dest: "{{ neofetch_directory }}/config"
    mode: "0600"
