---
- name: "Copy argon1.sh script"
  copy:
    src: "argon1.sh"
    dest: "/usr/local/bin/argon1.sh"
    mode: "0755"
  become: yes

- name: "Copy argononed configuration"
  template:
    src: "argononed.conf.j2"
    dest: "{{ argononed_conf_path }}"
    mode: "0644"
  become: yes

- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"
  become: yes

- name: "Start and enable SSH"
  systemd:
    name: "ssh"
    state: "restarted"
    enabled: yes
  become: yes

- name: "Install utilities"
  apt:
    name:
      - "ntfs-3g"
      - "ansible"
      - "firefox-esr"
      - "git"
      - "borgbackup"
  become: yes
