---
- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"
  become: yes

- name: "Start and enable SSH"
  systemd:
    name: "ssh"
    state: "restarted"
    enabled: yes
  become: yes

- name: "Install utilities"
  apt:
    name:
      - "ntfs-3g"
      - "ansible"
      - "firefox-esr"
      - "git"
      - "borgbackup"
  become: yes

- name: Check if argononed is installed
  stat:
    path: "/usr/bin/argonone-config"
  register: argonone

- name: "Download Argon One installer"
  get_url:
    url: "{{ argon1_url }}"
    dest: "/tmp/argon1.sh"
    mode: "0755"
    checksum: "{{ argon1_checksum }}"
  when: not argonone.stat.exists

- name: "Run Argon One installer"
  command:
    cmd: "/tmp/argon1.sh"
  when: not argonone.stat.exists
