---
- name: "Create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    shell: "/bin/bash"
    state: "present"

- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"
