---
- name: "Create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    shell: "/bin/bash"
    state: "present"

- name: "Set authorized key from local user"
  authorized_key:
    user: "{{ general_user }}"
    key: "{{ lookup('file', '~/.ssh/raspberry_id_rsa.pub') }}"
    state: "present"

- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"

- include_role:
    name: "general"
    tasks_from: "scripts"
  with_items:
    - "shelp"
    - "svlc"
    - "player-control"
    - "volume"
  loop_control:
    loop_var: "script"

- name: "Install utilities"
  apt:
    name:
      - "omxplayer"
      - "cec-utils"
      - "xscreensaver"
