---
- name: "Create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    state: "present"
  become: yes

- name: "Set authorized key from local user"
  block:
    - stat: path="~/.ssh/raspberry_id_rsa.pub"
      register: raspberry_pi_key
    - authorized_key: user="{{ general_user }}" key="{{ lookup('file', '~/.ssh/raspberry_id_rsa.pub') }}" state="present"
      when: raspberry_pi_key is defined and raspberry_pi_key.stat.islnk is defined
  become: yes

- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"
  become: yes

- name: "Install utilities"
  apt:
    name:
      - "ntfs-3g"
      - "ansible"
      - "firefox-esr"
      - "git"
  become: yes

- name: "Generate SSH keys"
  user:
    name: "{{ item.owner }}"
    generate_ssh_key: yes
    ssh_key_file: ".ssh/{{ item.service }}_id_{{ item.type }}"
    ssh_key_type: "{{ item.type }}"
    ssh_key_passphrase: "{{ item.passphrase }}"
    ssh_key_comment: "{{ item.owner }} - {{ item.service }}"
  with_items: "{{ general_ssh_keys }}"
  no_log: yes
  register: ssh_keys_created

- name: "Setup Github with SSH key"
  block:
    - known_hosts: path="~/.ssh/known_hosts" name="github.com" key="{{ github_host }}"
      with_items: "{{ ssh_keys_created.results | selectattr('ssh_key_file', 'search', 'github') | list }}"
    - github_key: name="[Raspberry PI] {{ item.name }}" pubkey="{{ item.ssh_public_key }}" token="{{ general_github_access_token }}"
      with_items: "{{ ssh_keys_created.results | selectattr('ssh_key_file', 'search', 'github') | list }}"
      when: group_names[0] != "vagrant"
  when: ssh_keys_created is defined
  no_log: yes
