---
- name: "Create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    shell: "/bin/bash"
    state: "present"
  become: yes

- name: "Set authorized key from local user"
  block:
    - stat: path="~/.ssh/raspberry_id_rsa.pub"
      register: raspberry_pi_key
    - authorized_key: user="{{ general_user }}" key="{{ lookup('file', '~/.ssh/raspberry_id_rsa.pub') }}" state="present"
      when: raspberry_pi_key is defined and raspberry_pi_key.stat.islnk is defined
  become: yes

- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"
  become: yes

- include_role:
    name: "zsh"
    tasks_from: "scripts"
  with_items:
    - "shelp"
  loop_control:
    loop_var: "script"

- name: "Install utilities"
  apt:
    name:
      - "ntfs-3g"
      - "ansible"
      - "firefox-esr"
  become: yes
