---
- name: "Install zsh"
  apt:
    name:
      - "zsh"
      - "zsh-autosuggestions"
    state: "present"
  become: yes

- name: "Change default shell to zsh"
  user:
    name: "{{ general_user }}"
    shell: "/usr/bin/zsh"
  become: yes

- name: "Copy dircolors configuration file"
  template:
    src: "dircolors.j2"
    dest: "~/.dircolors"
    mode: "0600"

- import_tasks: "configurations.yml"
- import_tasks: "ripgrep.yml"
