---
- name: "Install Kodi"
  apt:
    name:
      - "kodi"
      - "kodi-pvr-hts"
  become: yes

- name: "Create folder for different Media"
  file:
    path: "{{ media_folder }}/{{ item }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "TV Shows"
    - "Movies"

- name: "Create remote keymap folder"
  file:
    path: "{{ media_kodi_configuration }}/userdata/keymaps"
    mode: "0755"
    state: "directory"

- name: "Copy remote keymaps configuration"
  template:
    src: "kodi/remote.xml.j2"
    dest: "{{ media_kodi_configuration }}/userdata/keymaps/remote.xml"
    mode: "0644"
  notify:
    - "Copy remote keymaps configuration"

- name: "Set GUI settings"
  lineinfile:
    path: "{{ media_kodi_configuration }}/guisettings.xml"
    regexp: ".*\"{{ item.option }}\".*"
    line: "    <setting id=\"{{ item.option }}\">{{ item.value }}</setting>"
    state: present
  with_items: "{{ media_kodi_options }}"
  notify:
    - "Set Kodi GUI settings"
