---
- name: "Create folder for media"
  file:
    path: "{{ media_folder }}"
    mode: "0755"
    state: "directory"

- name: "Install utilities"
  apt:
    name: "cec-utils"
  become: yes

- import_tasks: "kodi.yml"
- import_tasks: "spotify.yml"
