---
- name: "Install VLC"
  apt:
    name: "vlc"
  become: yes

- name: "Add relevant groups to VLC user"
  user:
    name: "{{ media_vlc_user }}"
    groups:
      - "audio"
      - "video"
    append: yes
    state: "present"
  become: yes

- name: "Create user systemd folder"
  file:
    path: "{{ user_systemd_directory }}"
    mode: "0755"
    state: "directory"

- name: "Copy VLC systemd"
  template:
    src: "vlc.service.j2"
    dest: "{{ user_systemd_directory }}/vlc.service"
    mode: "0644"
  notify: "Restart VLC"

- name: "Start/Enable VLC"
  systemd:
    name: "vlc"
    state: "started"
    enabled: yes
    daemon_reload: yes
    scope: "user"
