---
- hosts: production

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  roles:
    - { role: "general", tags: "general" }
    - { role: "media", tags: "media" }
    - { role: "editor", tags: "editor" }
    - { role: "torrents", tags: "torrents" }
    - { role: "zsh", tags: "zsh" }
    - { role: "shell", tags: "shell" }
    - { role: "sync", tags: "sync" }
    - { role: "network", tags: "network" }

  post_tasks:
    - name: "Display message about how to execute argon script"
      debug:
        msg: "Please run '/usr/local/bin/argon1.sh'"
