---
- hosts: vagrant

  vars:
    user: "vagrant"

  pre_tasks:
    - name: "Update current packages"
      apt:
        upgrade: "yes"
        update_cache: yes
        force_apt_get: yes
      tags: "always"

  roles:
    - { role: "general", tags: "general" }
    - { role: "media", tags: "media" }
    - { role: "editor", tags: "editor" }
    - { role: "torrents", tags: "torrents" }
    - { role: "zsh", tags: "zsh" }
    - { role: "shell", tags: "shell" }
    - { role: "sync", tags: "sync" }
    - { role: "network", tags: "network" }
