---
- name: "Restart spotifyd"
  systemd:
    name: "spotifyd"
    state: "restarted"
  become: yes

- name: "Stop Kodi"
  systemd:
    name: "kodi"
    state: "stopped"
  become: yes

- name: "Copy remote keymaps configuration"
  template:
    src: "kodi/remote.xml.j2"
    dest: "{{ media_kodi_configuration }}/userdata/keymaps/remote.xml"
    mode: "0644"

- name: "Set Kodi GUI settings"
  lineinfile:
    path: "{{ media_kodi_configuration }}/guisettings.xml"
    regexp: ".*\"{{ item.option }}\".*"
    line: "    <setting id=\"{{ item.option }}\">{{ item.value }}</setting>"
    state: present
  with_items: "{{ media_kodi_options }}"

- name: "Restart Kodi"
  systemd:
    name: "kodi"
    state: "restarted"
  become: yes
